### ISSUE TITLE
PHP integration

### ISSUE THREAD

**Issue by joshbmarshall** [airwallex/airwallex-payment-demo#34]
Hi I see that you have PHP integration as a coming-soon - is the intention to make an Omnipay or Payum module that we can use?

I'm considering using your payment gateway for my custom ecommerce platform (on https://www.sanchia.com.au ) but wanting to know how far away your PHP integration is or whether I'm better to write something myself.

If I write something myself I'm more than happy to release as open source so other PHP projects can use it.

**Comment by chao-ding-awx** [comment]
Sorry, @joshbmarshall 
PHP is not part of our priority right now, as it's just an integration demo. You could still using our js library to deal with the payment in your PHP website. 
If you want some demonstration, I think the CDN integration is the best for you. It's in native js and could show you how it works. If you have any other question, please contact our sales team ant they would be happy to give you a suitable solution for your customer.
Thanks again for your attention.
