### ISSUE TITLE
Error: Forbidden

### ISSUE THREAD

**Issue by jy967845** [airwallex/airwallex-payment-demo#64]
"Error: Forbidden
Your client does not have permission to get URL /assets/elements.bundle.min.js from this server."

This error is showing in Japan when accessing https://checkout.airwallex.com/assets/elements.bundle.min.js.

My Japanese customers are not able to make payment on my website using Airwallex because script is not accessible so it is showing error.
![Screenshot_247](https://user-images.githubusercontent.com/41678444/201027887-5e96e72f-59e5-4fbc-96c6-1b0184cae35f.png)

**Comment by chao-ding-awx** [comment]
If you still have this issue, please raise a ticket here: https://help.airwallex.com/hc/en-gb/requests/new. Thank you.
