### ISSUE TITLE
payment_method.type must be provided

### ISSUE THREAD

**Issue by quanglatte** [airwallex/airwallex-payment-demo#69]
Hello

I create a Paymen Intent as follows
`{
    "amount": 100.01,
    "currency": "USD",
    "merchant_order_id": "126",    
    "payment_method_options": {
        "card": {
            "risk_control": {
                "skip_risk_processing": false,
                "three_domain_secure_action": "FORCE_3DS",
                "three_ds_action": "FORCE_3DS"
            },
            "three_ds_action": "FORCE_3DS"
        }  
    },
    "request_id": "126",
    "return_url": "http://www.example.com"
}`
Then I make the confirm API call
The return I get is:
`{
    "code": "validation_error",
    "source": "payment_method.type",
    "message": "payment_method.type must be provided"
}`
In the API description I don't see the parameter payment_method description!!!
Please tell me why and how to fix it

**Comment by chao-ding-awx** [comment]
I think this should be fixed if you use the latest version elements. If you still have this issue, please raise a support ticket here: https://help.airwallex.com/hc/en-gb/requests/new. Thank you.
