### ISSUE TITLE
onSubmit not working in the nextjs

### ISSUE THREAD

**Issue by lynn1286** [airwallex/airwallex-payment-demo#70]

**Comment by lynn1286** [comment]
<img width="863" alt="image" src="https://user-images.githubusercontent.com/40122311/216301333-392c134b-c8c0-4005-8885-d6c3ddce7c93.png">

**Comment by shirly-chen-awx** [comment]
@lynn1286 do you still experience this issue? If yes, could you maybe send a link or provide a jsfiddle demo where I can reproduce the issue?

**Comment by chao-ding-awx** [comment]
@lynn1286 If you still experience this, please raise your request at https://help.airwallex.com/hc/en-gb/requests/new.
