### ISSUE TITLE
"export 'default' (imported as 'Airwallex') was not found in 'airwallex-payment-elements'

### ISSUE THREAD

**Issue by dillonbailey** [airwallex/airwallex-payment-demo#75]
**Version**
"airwallex-payment-elements": "^0.2.103",

**Issue**
Attempting to import Airwallex from airwallex-payment-elements fails with the error as below:

![Screenshot 2023-04-03 at 5 29 29 pm](https://user-images.githubusercontent.com/1067872/229441122-2f1c94be-831f-49b4-8f01-cc188720593d.png)

**Comment by shirly-chen-awx** [comment]
can you try this way?
`import { redirectToCheckout, loadAirwallex } from 'airwallex-payment-elements';`

**Comment by dillonbailey** [comment]
@shirly-chen-awx - thank you - that is now working.

Can you also clariy, docs are a bit fuzzy on this, but do we need `loadAirwallex`? It seems to only set the environment, which is also done during the `redirectToCheckout` call (ref: https://codesandbox.io/s/github/airwallex/airwallex-payment-demo/tree/master/integrations/react-ts?from-embed=&initialpath=/hpp&file=/src/components/hpp.tsx)

Cheers.

**Comment by shirly-chen-awx** [comment]
@dillonbailey yes, we need `loadAirwallex` before `redirectToCheckout`, loadAirwallex not only sets the env, but also load airwallex element js.

**Comment by dillonbailey** [comment]
Thanks @shirly-chen-awx
