### ISSUE TITLE
Airwallex.RedirectToCheckout produces "undefined" error on Hosted Payment Page

### ISSUE THREAD

**Issue by dillonbailey** [airwallex/airwallex-payment-demo#76]
**Version**
Using https://checkout.airwallex.com/assets/elements.bundle.min.js as import is failing, refer to https://github.com/airwallex/airwallex-payment-demo/issues/75

**Issue**

Our call looks like the below:
```
          Airwallex.redirectToCheckout({
            env: 'demo', // Which env('staging' | 'demo' | 'prod') you would like to integrate with
            intent_id: data.id,
            client_secret: data.client_secret,
            currency: 'AUD',
          });
```

RedirectToCheckout produces a blank airwallex page: https://checkout-demo.airwallex.com/#/standalone/checkout/undefined?currency=AUD&from=http://localhost:3000&sessionId=bfbdec2c-ad2c-4766-a178-de22f13e7627

![Screenshot 2023-04-03 at 5 37 31 pm](https://user-images.githubusercontent.com/1067872/229442634-74ad77c2-59bf-49c9-b19c-1a3c840b3546.png)

**Notes**
- we can see the intent created in the demo account (https://demo.airwallex.com/app/acquiring/list/details/fa2ed50f-b21c-4546-bc83-37ab40acebe2/int_hkdmbphncgjoty0vln2)

_Sidenote: attempting to use versioned hosted bundles that are versioned, e.g. https://checkout.airwallex.com/assets/bundle.0.2.103.min.js - does not appear to work as expected as this serves a HTML page, not the library._

**Comment by shirly-chen-awx** [comment]
Hi, @dillonbailey, could you check your` data.id `and `data.client_secret` to make sure they are not `undefined`?

**Comment by dillonbailey** [comment]
Ah too right @shirly-chen-awx - thank you! In trying to get the library loading I overlooked my data structure!

Thank you!
