### ISSUE TITLE
Payment Demo Sandbox Not Working

### ISSUE THREAD

**Issue by dillonbailey** [airwallex/airwallex-payment-demo#78]
**Issue**
The demo sandbox linked from this page https://www.airwallex.com/docs/online-payments__hosted-payment-page - does not appear to be working.

https://codesandbox.io/s/github/airwallex/airwallex-payment-demo/tree/master/integrations/react-ts?from-embed&initialpath=%2Fhpp

**Comment by shirly-chen-awx** [comment]
hey, can you try this [url](https://codesandbox.io/s/github/airwallex/airwallex-payment-demo/tree/master/integrations/react-ts?from-embed&initialpath=%2Fhpp) again? Besides, we found the codesandbox cdn is not stable, so we removed it in product doc.

**Comment by dillonbailey** [comment]
Thanks @shirly-chen-awx - that updated link is working now and v. helpful.

DB
