### ISSUE TITLE
Return URL not respected for PaymentIntent

### ISSUE THREAD

**Issue by dillonbailey** [airwallex/airwallex-payment-demo#80]
**Describe the bug**
Setting the `return_url` when creating a payment intent does not redirect the user back to that location after successful payment.

**To Reproduce** Steps to reproduce the behavior, better to provide the link to reproduce:

1. Generate a payment link with the demo api
2. Set the return_url
3. Complete a payment on the HPP related to the payment link
4. You are not redirected back to the return_url set in step #2

**Expected behavior**
You are redirected to the correct page.

**Screenshots** If applicable, add screenshots to help explain your problem.

**Integration information:**
- language
  - [ ] angular
  - [x] cdn - npm 
  - [ ] node
  - [ ] react
  - [ ] react-ts
  - [ ] ReactNative
  - [ ] vue

- element
  - [x] hpp
  - [ ] dropIn element
  - [ ] card element
  - [ ] split card element
  - [ ] full featured card element
  - [ ] applePay element
  - [ ] googlePay element
**Contexts:**
- Integration env (e.g. demo): Demo
- IntentId: 
- Device (e.g. iPhone12):
- OS (e.g. iOS8.1):
- Browser (e.g. stock browser, safari):
- Language:

**Additional context** Add any other context about the problem here.

**Comment by shirly-chen-awx** [comment]
Hi, @dillonbailey 
Thanks for raising this issue!
For hpp, there is no need to pass `return_url`. we should pass `successUrl` and `failUrl` into `redirectToCheckout` function. 
Your idea is also correct, but we do not support it for hpp yet.

**Comment by dillonbailey** [comment]
Thanks @shirly-chen-awx - would recommend updating the documentation here: https://www.airwallex.com/docs/api#/Payment_Acceptance/Payment_Intents/_api_v1_pa_payment_intents_create/post that this does not apply for HPP

Where are you getting the documentation for `successUrl` and `failUrl`? I can't see anything related here: https://www.npmjs.com/package/airwallex-payment-elements/v/0.3.2

**Comment by shirly-chen-awx** [comment]
yes, will update the doc.

you can check the doc here. -> https://github.com/airwallex/airwallex-payment-demo/tree/master/docs
