### ISSUE TITLE
Subscription payments

### ISSUE THREAD

**Issue by redimongo** [airwallex/airwallex-payment-demo#82]
Is there away to handle subscriptions via this plugin?

This question is related to:
- language
 
  - [x ] react-ts
  
- element
  - [ ] hpp
  - [ x] dropIn element
  - [ ] card element
  - [ ] split card element
  - [ ] full featured card element
  - [ ] applePay element
  - [ ] googlePay element

**Comment by redimongo** [comment]
From what I have read, seems we need to use the fullFeaturedCard. 

But I am having issues making it realise that the card needs to be saved, as default the check box in unchecked.

I have tried to add the code to

```
 intent: {
            // Required, must provide intent details to prepare fullFeaturedCard element
            id: intent_id,
            client_secret,
            mode: "recurring",
            recurringOptions: true,
          }
          
```

But the checkbox remands unchecked.

**Comment by chao-ding-awx** [comment]
Hi RUSSELL, could you raise your request on Airwallex support desk so that our Merchant solution team could see your request and help you with this.
https://help.airwallex.com/hc/en-gb/requests/new
